name: Build and Bundle MacOS (x64 and arm64)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_macos_x64:
    # if: false  # This workflow is disabled
    runs-on: macos-latest
    strategy:
      matrix:
        arch: [x64]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Build wariosave
      run: |
        cd lib
        mkdir -p build/release
        make release

    - name: Publish Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: wariosave-artifacts-macos-x64
        path: lib/build/release

  build_macos_arm64:
    # if: false  # This workflow is disabled
    runs-on: macos-latest
    strategy:
      matrix:
        arch: [arm64]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Test tools
        run: |
          brew install cunit cppcheck
  
      - name: Build wariosave
        run: |
          cd lib
          mkdir -p build/release
          make release

      - name: Run Tests
        run: |
          cppcheck --std=c11 --enable=all --inconclusive --suppress=missingInclude --suppress=missingIncludeSystem --suppress=unusedFunction lib/src/ || true
          cd test/
          make test
  
      - name: Publish Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: wariosave-artifacts-macos-arm64
          path: lib/build/release
